apiVersion: v2
name: vllm-stack
description: The stack deployment of vLLM
type: application

# Chart version. Bump on every change to the chart or its templates.
# Follows Semantic Versioning (https://semver.org/).
version: 0.2.0

